Implementing safe_gather
HeavenVolkoff/async_tools pull request #2
Opened 2021-05-24 13:36 UTC by fogodev

A function to gather and wait awaitablesbut cancelling remaining awaitables in case of exception

2021-05-24 19:42 UTC, HeavenVolkoff requested changes
Hi, I like the concept for this function, and can see valid use cases for it. However, there some problems with the current implementation that I need you to fix before I can merge this:

1. Revert all changes to `setup.cfg`, version changes are not the scope of the PR, and there is no reason to change the current mypy configuration.

2. Don't use `kwargs` for forwarding extra arguments to `gather`. Its api is stable, and this should explicitly define the same argument list as `gather`. To avoid subtle bugs due to incorrect type hints in tools and Ides. 

3. `gather` receives, as argument, a list of awaitables, which it then transforms to futures internally. The way your function currently behaviors may present inconsistency, due to how it handles awaitables exceptions, as it again transforms the awaitable into another future object, different from the one used internally by gather. My suggestion is to do a map of the awaitables, transforming them all to futures, before calling gather, which will ensure that the future object inside gather and outside will be the same

4. There is no need to check if a future is done before calling cancel, cancel works either way, in cases where the future is already done when calling cancel it will act as a nop.

2021-05-25 19:58 UTC, HeavenVolkoff approved these changes

2021-05-25 20:39 UTC, HeavenVolkoff commented
@fogodev I improved the implementation, and added some tests. I think it is now fine for merging, could you test and see if it still correctly covers your use case.

2021-05-25 20:43 UTC, fogodev commented
Looks even better now, more resilient to weird stuff. It kept working on my local tests. Thanks

2021-05-25 20:46 UTC, merged